#pragma once
#include <openxr/openxr.h>
#include <array>

namespace HMDVariable {
    inline constexpr int GL_VIEW_WIDTH           = 500;
    inline constexpr int GL_VIEW_HEIGHT           = 500;
    inline constexpr int SWAPCHAIN_WIDTH           = 1024;
    inline constexpr int SWAPCHAIN_HEIGHT           = 768;
    
}

inline constexpr std::array<int, 27> kSpecificIndices = {
    XR_HAND_JOINT_PALM_EXT,
    XR_HAND_JOINT_WRIST_EXT,
    XR_HAND_JOINT_THUMB_METACARPAL_EXT,
    XR_HAND_JOINT_THUMB_PROXIMAL_EXT,
    XR_HAND_JOINT_THUMB_DISTAL_EXT,
    XR_HAND_JOINT_THUMB_TIP_EXT,
    XR_HAND_JOINT_INDEX_METACARPAL_EXT,
    XR_HAND_JOINT_INDEX_PROXIMAL_EXT,
    XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT,
    XR_HAND_JOINT_INDEX_DISTAL_EXT,
    XR_HAND_JOINT_INDEX_TIP_EXT,
    XR_HAND_JOINT_MIDDLE_METACARPAL_EXT,
    XR_HAND_JOINT_MIDDLE_PROXIMAL_EXT,
    XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT,
    XR_HAND_JOINT_MIDDLE_DISTAL_EXT,
    XR_HAND_JOINT_MIDDLE_TIP_EXT,
    XR_HAND_JOINT_RING_METACARPAL_EXT,
    XR_HAND_JOINT_RING_PROXIMAL_EXT,
    XR_HAND_JOINT_RING_INTERMEDIATE_EXT,
    XR_HAND_JOINT_RING_DISTAL_EXT,
    XR_HAND_JOINT_RING_TIP_EXT,
    XR_HAND_JOINT_LITTLE_METACARPAL_EXT,
    XR_HAND_JOINT_LITTLE_PROXIMAL_EXT,
    XR_HAND_JOINT_LITTLE_INTERMEDIATE_EXT,
    XR_HAND_JOINT_LITTLE_DISTAL_EXT,
    XR_HAND_JOINT_LITTLE_TIP_EXT
};

// Index, middle, ring fingers only (metacarpal & intermediate)
inline constexpr std::array<int, 6> FINGER_JOINT_INDICES = {
    XR_HAND_JOINT_INDEX_METACARPAL_EXT,
    XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT,
    XR_HAND_JOINT_MIDDLE_METACARPAL_EXT,
    XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT,
    XR_HAND_JOINT_RING_METACARPAL_EXT,
    XR_HAND_JOINT_RING_INTERMEDIATE_EXT
};

// Four tip joints (thumb, index, middle, ring)
inline constexpr std::array<int, 4> kTipIndices = {
  XR_HAND_JOINT_THUMB_TIP_EXT,
  XR_HAND_JOINT_INDEX_TIP_EXT,
  XR_HAND_JOINT_MIDDLE_TIP_EXT,
  XR_HAND_JOINT_RING_TIP_EXT
};

// Four intermediate joints
inline constexpr std::array<int, 4> kIntermediateIndices = {
  XR_HAND_JOINT_THUMB_DISTAL_EXT,
  XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT,
  XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT,
  XR_HAND_JOINT_RING_INTERMEDIATE_EXT
};

// Four root positions (wrist + one proximal per finger)
inline constexpr std::array<int, 4> kRootIndices = {
  XR_HAND_JOINT_WRIST_EXT,
  XR_HAND_JOINT_INDEX_PROXIMAL_EXT,
  XR_HAND_JOINT_MIDDLE_PROXIMAL_EXT,
  XR_HAND_JOINT_RING_PROXIMAL_EXT
};

// Four local frames (wrist orientation + 3 metacarpals)
inline constexpr std::array<int, 4> kLocalFrameIndices = {
  XR_HAND_JOINT_WRIST_EXT,
  XR_HAND_JOINT_INDEX_METACARPAL_EXT,
  XR_HAND_JOINT_MIDDLE_METACARPAL_EXT,
  XR_HAND_JOINT_RING_METACARPAL_EXT
};

