#pragma once
#include <openxr/openxr.h>

namespace HMDVariable {
    inline constexpr int GL_VIEW_WIDTH           = 500;
    inline constexpr int GL_VIEW_HEIGHT           = 500;
    inline constexpr int SWAPCHAIN_WIDTH           = 1024;
    inline constexpr int SWAPCHAIN_HEIGHT           = 768;
    
}

inline const std::vector<int> kSpecificIndices = 
{
    XR_HAND_JOINT_PALM_EXT,
    XR_HAND_JOINT_WRIST_EXT,
    XR_HAND_JOINT_THUMB_METACARPAL_EXT,
    XR_HAND_JOINT_THUMB_PROXIMAL_EXT, 
    XR_HAND_JOINT_THUMB_DISTAL_EXT, 
    XR_HAND_JOINT_THUMB_TIP_EXT, 
    XR_HAND_JOINT_INDEX_METACARPAL_EXT, 
    XR_HAND_JOINT_INDEX_PROXIMAL_EXT, 
    XR_HAND_JOINT_INDEX_INTERMEDIATE_EXT ,
    XR_HAND_JOINT_INDEX_DISTAL_EXT ,
    XR_HAND_JOINT_INDEX_TIP_EXT ,
    XR_HAND_JOINT_MIDDLE_METACARPAL_EXT ,
    XR_HAND_JOINT_MIDDLE_PROXIMAL_EXT ,
    XR_HAND_JOINT_MIDDLE_INTERMEDIATE_EXT,
    XR_HAND_JOINT_MIDDLE_DISTAL_EXT ,
    XR_HAND_JOINT_MIDDLE_TIP_EXT ,
    XR_HAND_JOINT_RING_METACARPAL_EXT ,
    XR_HAND_JOINT_RING_PROXIMAL_EXT ,
    XR_HAND_JOINT_RING_INTERMEDIATE_EXT ,
    XR_HAND_JOINT_RING_DISTAL_EXT ,
    XR_HAND_JOINT_RING_TIP_EXT ,
    XR_HAND_JOINT_LITTLE_METACARPAL_EXT ,
    XR_HAND_JOINT_LITTLE_PROXIMAL_EXT ,
    XR_HAND_JOINT_LITTLE_INTERMEDIATE_EXT ,
    XR_HAND_JOINT_LITTLE_DISTAL_EXT ,
    XR_HAND_JOINT_LITTLE_TIP_EXT ,
};
